### ISSUE TITLE
Make it possible to pass in a custom messageId

### ISSUE THREAD

**Issue by eladnava** [moscajs/aedes-packet#1]
Hi @mcollina!

Just wondering, is it possible to modify `aedes-packet` so we can pass in our own `messageId` for tracking purposes?
https://github.com/mcollina/aedes-packet/blob/6b3497ed99fca4ac6c7e308953516ee8d82f8b33/packet.js#L11

Can I submit a PR?

Thanks!

**Comment by eladnava** [comment]
Also, would be nice if we could set other fields on the `aedes-packet` that we can later utilize in the `ack` event to identify the acknowledged message.

**Comment by mcollina** [comment]
Some notes:

a. I would call `messageId` a **locked** field, as it defined by the MQTT spec.
b. the ACK packet format is fixed

What's your use case?

**Comment by eladnava** [comment]
My use case is that I have a collection of messages in my database that I send to a connected client, and later want to identify the ones that have been ACKed back, so I can mark them as "received" in my database.

My way of doing that was assigning my own `messageId` in Mosca, then linking the messageId to the database reference of the message, and in the `ack` event, use the messageId of the acked packet to get the database ref. I would then mark the message as read in my database.

I now realize that injecting a custom `messageId` is dangerous. 

Could we instead allow passing in custom properties to `aedes-packet`? For example, a `metadata` object:

```
  this.metadata = original.metadata || {}
```

It doesn't have to be called `metadata`, I just need a way to save my database reference onto the packet, and get it back when the device ACKs.

**Comment by mcollina** [comment]
@eladnava I do not think that usecase can be supported without a massive refactoring. Maybe you However I think you can use this: https://github.com/mcollina/aedes/blob/master/lib/handlers/puback.js#L6 and store your unique id into the message itself.

**Comment by eladnava** [comment]
Are you referring to storing it inside the actual publish payload, and then extracting it in the `ack` event? That would mean it would be delivered to the client, something I would like to avoid.

There is actually no need for massive refactoring! I have simply added the following line in `packet.js`:

```
this.deliveryId = original.deliveryId;
```

I then published the module `aedes-packet-deliveryid` and modified both `aedes` and `aedes-persistence` to use my `aedes-packet-deliveryid` package instead of `aedes-packet`.

That's all that was necessary for Aedes to preserve my `deliveryId` property on the `packet` which I pass in to `client.publish(packet, callback)`. Every time Aedes would create a new packet out of an existing packet, the `deliveryId` would be passed on.

I have verified this work and I do get the `deliveryId` I published with my packet back in the `ack` event. I am using `MemoryPersistence` if that makes any difference.

I now use [aedes-deliveryid](https://www.npmjs.com/package/aedes-deliveryid) until I am able to pass in custom packet parameters.

**Comment by mcollina** [comment]
> There is actually no need for massive refactoring!

I disagree: all of that will work only with `MemoryPersistence`.

The same concept of a delivery id in Aedes is stored as the pair brokerId/brokerCount. That's unique.

**Comment by eladnava** [comment]
@mcollina I see. The problem is that the brokerId/brokerCount is not made available to me until the `ack` event. 

Maybe we can make the updated packet available in the `client.publish` callback, instead of a callback without any parameters? That way, I could access the brokerId/brokerCount after publishing and in the `ack` event as well.

**Comment by mcollina** [comment]
> Maybe we can make the updated packet available in the client.publish callback, instead of a callback without any parameters? That way, I could access the brokerId/brokerCount after publishing and in the ack event as well.

@eladnava that's a good idea. PR?

**Comment by eladnava** [comment]
@mcollina Sure, but I'm not exactly sure how to implement it.

`aedes.publish` uses `fastseries` and the last parameter is the `done` callback:

>   this._series(new PublishState(this, client, p), publishFuncs, null, done)

https://github.com/mcollina/aedes/blob/43982a1b1be9b4021e41f95033fca0047a32b5d6/aedes.js#L235

Not exactly sure how we can end up passing `p` to `done` which is the new packet.

**Comment by mcollina** [comment]
Closing because of https://github.com/mcollina/aedes/issues/66#issuecomment-249164677.
