### ISSUE TITLE
Set messageId be undefined

### ISSUE THREAD

**Issue by gnought** [moscajs/aedes-packet#4]
I think we should delete the messageId

If messageId exists, the `QoSPacket` can't have a right messageId
https://github.com/mcollina/aedes/blob/master/lib/client.js#L118
https://github.com/mcollina/aedes/blob/master/lib/qos-packet.js#L11

Also after going a deep analysis,
1. `outgoingEnqueue` https://github.com/mcollina/aedes-persistence/blob/master/persistence.js#L170 and `outgoingEnqueueCombi` https://github.com/mcollina/aedes-persistence/blob/master/persistence.js#L218 functions in aedes-persistence should not store messageId
2. `deliverQoS` https://github.com/mcollina/aedes/blob/master/lib/client.js#L110 will assign a right messageId when we create `QoSPacket` for message delivery. `outgoingUpdate` function https://github.com/mcollina/aedes-persistence/blob/master/persistence.js#L206 will then update the messageId in the queue.

What do you think?
If this is the case, we need to modify some tests in aedes-persistence like https://github.com/mcollina/aedes-persistence/blob/master/abstract.js#L745

**Comment by mcollina** [comment]
set it to `undefined`.

**Comment by gnought** [comment]
Let me try in my local branch. :)

**Comment by gnought** [comment]
In some tests, when we match packet by `deepEqual`, we get the following:
```
      operator: deepEqual
      expected: |-
        [ { cmd: 'publish', topic: 'hello', payload: <Buffer 77 6f 72 6c 64>, qos: 1, retain: false, brokerId: 'broker-42', brokerCounter: 42 } ]
      actual: |-
        [ { cmd: 'publish', brokerId: 'broker-42', brokerCounter: 42, topic: 'hello', payload: <Buffer 77 6f 72 6c 64>, qos: 1, retain: false, messageId: undefined } ]
```

Likely we need to delete the messageId before deepEqual comparison. Fine for that?

or we need to define the messageId as `undefined` like
```
var expected = {
      cmd: 'publish',
      topic: 'hello',
      payload: Buffer.from('world'),
      qos: 1,
      retain: false,
      brokerId: instance.broker.id,
      brokerCounter: 42,
      messageId: undefined
    }
```

**Comment by mcollina** [comment]
yes

Il giorno mer 17 lug 2019 alle ore 15:09 Gnought <notifications@github.com>
ha scritto:

**Comment by mcollina** [comment]
even better, check that's undefined before deleting.

Il giorno mer 17 lug 2019 alle ore 15:15 Matteo Collina <
matteo.collina@gmail.com> ha scritto:
